---
title: "credits"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(rjson, jsonlite, DT,  RJSONIO, data.table, dplyr, compareDF)
```

```{r}
metadata = read.csv("../../../dataraw/credits.csv")
```

- CAST COLUMN -

```{r}
head(metadata$cast)
```

```{r}

metadata$cast <- gsub("'", '"', metadata$cast)
metadata$cast <- gsub('^$', '{}', metadata$cast)
metadata$cast <- gsub('None', '\\"None\\"', metadata$cast)
metadata$cast <- gsub('\\"     ', '', metadata$cast)
metadata$cast <- gsub(' \\"      \\w*\\"?', 

#metadata$cast <- gsub(" '", ' "', metadata$cast)
#metadata$cast <- gsub("':", '":', metadata$cast)
#metadata$cast <- gsub("'}", '"}', metadata$cast)
#metadata$cast <- gsub("\\{'", '\\{"', metadata$cast)
#metadata$cast <- gsub("\\\\xa0", '', metadata$cast)
#metadata$cast <- gsub("\"n'", '', metadata$cast)
#metadata$cast <- gsub('^$', '{}', metadata$cast)
```

```{r}
metadata_filtered <- metadata %>% 
  filter(cast != '[]')
```

```{r}
metadata_filtered$val <- lapply(metadata_filtered$cast, validate)

sum(metadata_filtered$val == "TRUE")

```

```{r}
cast_list <- list()
cast_df <- data.frame()
row <- data.frame()


for (i in metadata_filtered$cast) {
  row <- fromJSON(i)
  cast_list <- c(cast_list, list(row))
}

dfs <- lapply(cast_list, data.frame, stringsAsFactors = FALSE)

cast_df <- rbindlist(dfs, fill = T)

metadata_filtered <- cbind(metadata_filtered, cast_df)
```


```{r}
write.csv(metadata_filtered, file = "filtered/keywords_filtered.csv")
```