---
title: "keywords"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(rjson, jsonlite, DT,  RJSONIO, data.table, dplyr, compareDF)
```

```{r}
metadata = read.csv("../../../dataraw/keywords.csv")
```

```{r}
head(metadata$keywords)
```

```{r}
metadata$keywords <- gsub("'", '"', metadata$keywords)
metadata$keywords <- gsub('^$', '{}', metadata$keywords)
```

```{r}
metadata_filtered <- metadata %>% 
  filter(keywords != '[]')
```

```{r}
keywords_list <- list()

as.data.frame(fromJSON(metadata_filtered[1, 'keywords']))

keywords_df <- data.frame()
row <- data.frame()

for (i in metadata_filtered$keywords) {
  row <- fromJSON(i)
  keywords_list <- c(keywords_list, list(row))
  
}

dfs <- lapply(genre_list, data.frame, stringsAsFactors = FALSE)

genre_df <- rbindlist(dfs, fill = T)

metadata_filtered <- cbind(metadata_filtered, genre_df)
```

```{r}
production_list <- list()

as.data.frame(fromJSON(metadata[1, 'genres']))

genre_df <- data.frame()
row <- data.frame()

for (i in metadata$genres) {
  row <- fromJSON(i)
  genre_list <- c(genre_list, list(row))
  
}

dfs <- lapply(genre_list, data.frame, stringsAsFactors = FALSE)

genre_df <- rbindlist(dfs, fill = T)

metadata_filtered <- cbind(metadata_filtered, genre_df)
```
