---
title: "Lucia"
author: "Lucia"
date: "04/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pacman)
pacman::p_load(dplyr, ggplot2, tidyr, ggpubr)
options(scipen = 999)
```

---

```{r Read in CSV file}
movie_metadata <- read.csv("./data/movie_metadata.csv", sep=";")
```

```{r fig.width=8}
movie_metadata %>%
  filter(imdb_score >6 ) %>% #Filter to show the graph only for vote_average values greater than 6
  na.omit() %>% 
 ggplot(aes(x = gross/1000000, y = content_rating), height=0) + 
  geom_jitter(alpha = 0.5, col = "darkred") + 
  theme(axis.text.x=element_text(angle = 90, hjust = 1))+
  ggtitle("Gross vs Content Rating")+
  xlab("Gross (millions)")+
  ylab("Rating") +
  geom_smooth() +
  coord_flip() 

```

```{r}
movie_metadata %>%
  filter(imdb_score >6 ) %>% 
  ggplot() + 
  geom_density(aes())
```

```{r fig.width=8}
movie_metadata %>%
  filter(imdb_score >6 ) %>% #Filter to show the graph only for vote_average values greater than 6
  na.omit() %>% 
 ggplot(aes(x = gross/1000000, y = genres), height=0) + 
  geom_jitter(alpha = 0.5, col = "darkred") + 
  theme(axis.text.x=element_text(angle = 90, hjust = 1))+
  ggtitle("Gross vs Genre")+
  xlab("Gross (millions)")+
  ylab("Genre") +
  geom_smooth() +
  coord_flip() 

```
