---
title: "Links"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Useful Links

> 1. Dataset

https://www.kaggle.com/rounakbanik/the-movies-dataset

-----

> 2. Grab some popcorn: Analysis of The Movie DataBase (TMDB)

https://rstudio-pubs-static.s3.amazonaws.com/384914_7bee8325659440ab9db1b3de36c37343.html

* Number of Movies Released Vs Month [Heatmap]
* Distribution of IMDB ratings
* Impact of Rating on ROI
* Analysis of Movie runtime
* Vote Counts over the years
* Populatity over the years
* Analysis of Budget and Revenue
* 3D view of the movies that made a profit

-----

> 3. IMDB Movies Analysis

https://rpubs.com/jasmine36/234304

* Most Successful Directors
* 20 Most Profitable Movies
* 20 Most Profitable Movies based on its Return on Investment
* Commercial success Vs Critical acclaim
* Top 20 genres with the most movies

-----

> 4. Project Report: IMDB 5000 Movie Dataset

http://rstudio-pubs-static.s3.amazonaws.com/342210_7c8d57cfdd784cf58dc077d3eb7a2ca3.html

* Histogram of Movie Released
* Top 20 movies based on its Profit
* Top 20 movies based on its Return on Investment
* Top 20 directors with highest average IMDB score
* Commercial Success v.s. Critical Acclaim
* Relation between number of facebook likes and imdb_score

-----

> 5. Movie Genre Overlappings, Ratings by Genre and Year

https://rpubs.com/ceshine/movies_dataset_gt_experiment?source=post_page-----2f37a340c23f----------------------

* Read and Clean Metadata
* Parse Genres
* Genre Statistics
* Reading Ratings
* Rating statistics by Genre
* Rating statistics by Genre and Year

-----

> 6. Movielens Recommendation System

http://rpubs.com/xinmeiz/movielens2

 * Loading datastes
 * Data snapshot
 * 20 most and least rated movies
 * Removing any records prior to 2000
 * Exclude the members who have rated too fee or too many
 * Extract into separate columns.
 * Separated into one category per row
 * Popular movie genres year by year
 * Look at rating per member, Visualization
 * Filter movies rated at least 10 times and fewer than 500 times.
 * What genres are most popular movies?
 * Create plot for how the ratings change across the year for genre of Action, Roman, Sci-fi and Western.
 * What the ages for the users have rated movies?

-----

> Possible ratios

 * The highest rated movies vs likes 
 * Worst rated movies
 * Highest rated genre
 
 * Number of critic reviews vs Facebok likes
 * Least rated movies
 
 *Country vs Budget
 *Country vs language
 *Country vs Aspect ratio
 *Country vs content rating
 *Content rating vs actor: to see who works in pg films
  directors fb likes vs rating
 
 * Budget vs year
 * Budget vs gross
 * IMDB score vs Budget
 * IMDB score vs Facebook likes 
 
 * Actor vs Genre
 * Actor 1 vs Actor 2 likes
 * Actor 1 vs critic reviews

 * Ratings vs Gross
 * Ratings vs budget
 * Ratings vs actor 1
 * Ratings vs actor 2
 * Ratings vs facebook likes 
 * Ratings vs genre 
 * Ratings vs director
 * Ratings of Sequels

 
-----


Our dataset example:
 * https://www.kaggle.com/karrrimba/understanding-movies-through-data
 