---
title: "R Notebook"
output: html_notebook
---

```{r}
pacman::p_load("stringr","ggplot2", "tidyr", "ngram")
setwd(getwd())
options(scipen = 999)
```

```{r}
IMDB <- read.csv("../movie_metadata.csv", sep=";")
```

```{r}
#Removing Duplicates
IMDB <- IMDB[!duplicated(IMDB), ]
```

```{r}
#Removing White-Spaces and Special Characters
IMDB$movie_title <- gsub("Â", "", as.character(factor(IMDB$movie_title)))
IMDB$movie_title <- str_trim(IMDB$movie_title, side = "right")
```

```{r}
IMDB <- subset(IMDB, select = -c(genres))
```

```{r}
# REMEMBER TO REMOVE THESE
colSums(sapply(IMDB, is.na))
```

```{r}
ggplot(data = IMDB, aes(x = imdb_score, y = movie_facebook_likes)) +
  geom_point() +
  stat_smooth(method="lm")
```


```{r}
movie_aspect_graph <- IMDB %>% 
  filter(aspect_ratio==1.85 | aspect_ratio==2.35) %>%
  mutate(aspect_ratio=as.character((aspect_ratio))) %>%
  ggplot() +
  geom_point(aes(x=aspect_ratio, y=movie_facebook_likes))
    
```


```{r fig.width=11, fig.height=5}
keywords_split <- str_split(IMDB$plot_keywords, pattern="[|]", n=5)
keywords_matrix <- do.call(rbind, strsplit(IMDB$plot_keywords, '[|]'))
keywords_df <- as.data.frame(keywords_matrix)

names(keywords_df) <- c("one", "two", "three", "four", "five")

keywords_one_col <- gather(keywords_df) %>% 
  select(value)

keyword_freq_graph <- 
  keywords_one_col %>%
  group_by(value) %>% 
  tally() %>% 
  filter(n >= 30) %>% 
  ggplot() +
  geom_bar(aes(x = value, y=n), stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("keyword") +
  ylab("frequency") +
  NULL

keyword_freq_graph
    

typeof(keywords_one_col$value)
```

```{r eval=F}
#write manipulated data to csv
write.csv(keywords_df, file="../data-out/extracted_keywords.csv")
```



